on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2         
    - name: Verify commit exists in origin/master
      run: |
        git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
        git branch --remote --contains | grep origin/master
    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
    - name: Build
      run: dotnet build --configuration Debug /p:Version=${VERSION}
    - name: Test
      run: dotnet test --configuration Debug /p:Version=${VERSION} --no-build
    - name: ✨ Setup .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: "6.0.x"
        include-prerelease: true         
    - name: Pack
      run: dotnet pack --configuration Debug /p:Version=${VERSION} --include-symbols -p:SymbolPackageFormat=snupkg --no-build --output .
    - name: Push GitHub
      run: dotnet nuget push Ninject.Extensions.Interception.ProxyAttributes.${VERSION}.nupkg --source https://nuget.pkg.github.com/hlavrencic/index.json --api-key ${GITHUB_TOKEN}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Push Nuget
      run: dotnet nuget push Ninject.Extensions.Interception.ProxyAttributes.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${NUGET_API_KEY}
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}       